### ISSUE TITLE
files : {"error":"file_not_found"}

### ISSUE THREAD

**Issue by wzcGGG** [fedebotu/clone-anonymous-github#1]
I used your repository to download the code for a paper, but the files in the subdirectories are: {"error":"file_not_found"}. 
URL is : https://anonymous.4open.science/r/1590ffb0-aa6b-4838-9d59-ae20cdd8df11/
The contents of the file show: {"error":"file_not_found"}

**Comment by fedebotu** [comment]
Hi there @wzcGGG !
Thanks for your report. It turns out there was a bug in the way folders are addressed under Windows (Windows has the directory separator `\` instead of `/`) which made the code not find the files on the server.
This should be fixed with the new release! Let me know if it works fine now ;)

**Comment by wzcGGG** [comment]
Hello, the problem has been solved. It works fine now. 
Thank you very much for your work.

**Comment by fedebotu** [comment]
Anytime!
